In [1]:
import pretty_midi
import glob
import joblib

In [2]:
# targetPattern = r"../raw_data/*/*/*/*/*.mid"
# midi_files_paths = glob.glob(targetPattern)

# for file in midi_files_paths:
#     try:
#         joblib.dump(pretty_midi.PrettyMIDI(file), f'../raw_data/pretty_midi/{file.split("/")[-1][:-4]}')
#     except:
#         pass

In [2]:
targetPattern = r"../raw_data/pretty_midi/*"
pretty_midi_files_paths = glob.glob(targetPattern)

In [61]:
import pandas as pd
df = pd.DataFrame(index=range(len(pretty_midi_files)), columns=['piano_roll'])

In [44]:
pretty_midi_files = []
for file in pretty_midi_files_paths[:10]:
    pretty_midi_files.append(joblib.load(file))

In [45]:
file1 = pretty_midi_files[0]

In [52]:
df

piano_roll
0        NaN

In [62]:
for i, file in enumerate(pretty_midi_files):
    df.piano_roll[i] = file.get_piano_roll()

In [68]:
import numpy as np

In [ ]:
np

In [73]:
for _ in df.piano_roll:
    for i in _:
        print(i)

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.